
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/sell?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /faust

logging:
  pattern:
    console: "%d - %msg%n"
#  path: log/tomcat/
  file: D:/log/tomcat/faust.log
